extends:
  - react-app
  - ../.eslintrc.yml
parserOptions:
  project: ./tsconfig.json
  tsconfigRootDir: './'
overrides:
  - files:
      - vite.config.ts
    parserOptions:
      project: ./tsconfig.node.json
